### ISSUE TITLE
How to show WeekView and Day View using AGCalendar Module? 

### ISSUE THREAD

**Issue by jpsubbarayalu** [Appgutta/AGCalendar#27]
Hi Chris,

i am implementing a Calendar application which consists of Month,Week and Day view.Can u please let me know how to show these views.

Also i can able to add events in the calendar.Its displaying in the Table.Then how to show event detail page in this Calendar Module.

Thanks,
Jayaprakash S

**Comment by ChrisRM** [comment]
There are no week/day-view, but the module allows you to list out all events, so you can create your own view.

Currently im not taking advantage of the iOS built-in "EKEventViewController", so you'll have to create the add/edit view yourself. The reason why I left that one out is because of the multiple datasources. The EKEventViewController works great for adding events to the EventKit datasource, but not for CoreData. Maybe I'll add a method to open the built-in view controller in the future, we'll see.
